### ISSUE TITLE
GitHub not happy with size

### ISSUE THREAD

**Issue by webhat** [seanmacentee/Social-Media-Dimensions-Cheatsheet#1]
Viewing it in Github is not possible. And Git isn't too happy with binary blobs of this size.

Is it possible to split this into smaller files?

**Comment by seanmacentee** [comment]
yeah it's not very lightweight... i'll do my best to optimise file size first and then split it in to files for each network to give people more options...

**Comment by webhat** [comment]
It also gave some font errors on opening, do you want me to open a separate issue for that?

**Comment by seanmacentee** [comment]
no it's cool, i'll keep fonts standard next time around
